name: Test

on:
    - push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      ports:
        - 8080
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Test with the Go CLI
        run: go test -v ./...
