name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      ports:
        - 8080
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install Dependencies
        run: |
          apt-get update -y
          apt-get install ca-certificates -y
          update-ca-certificates
          cd server
          go get .
      - name: Test with the Go CLI
        run: cd server && go test -v ./...
