name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      ports:
        - 8080
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install Dependencies
        run: |
          apt-get update -y
          apt-get install ca-certificates -y
          update-ca-certificates
          cd server
          go install .
      - name: Test with the Go CLI
        run: cd server && go test -v ./...
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
            cache-dependency-path: ./client/package-lock.json
      - run: npm ci
        working-directory: ./client
      - run: npm run build --if-present
        working-directory: ./client